config/routes.rb
Rails.application.routes.draw do
  get 'proprietario/show'
  root 'home#index'
  devise_for :proprietarios
  resources :imoveis
  resources :proprietarios

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(proprietario)
    alias_action :create, :read, :update, :destroy, to: :crud

    proprietario ||= Proprietario.new

    if proprietario.admin?
      can :manage, :all
    else
      can :crud, Imovel, proprietario_id: proprietario.id
      can :crud, Proprietario, id: proprietario.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/imovel.rb
# == Schema Information
#
# Table name: imoveis
#
#  id                     :bigint           not null, primary key
#  proprietario_id        :bigint
#  endereco               :string
#  area_terreno           :decimal(7, 2)
#  area_construida        :decimal(7, 2)
#  area_total             :decimal(7, 2)
#  aliquota               :decimal(7, 2)
#  valor_venal_terreno    :decimal(7, 2)
#  valor_venal_construcao :decimal(7, 2)
#  valor_venal_total      :decimal(7, 2)
#  aliquota_aplicada      :decimal(7, 2)
#  valor_imposto          :decimal(7, 2)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Imovel < ApplicationRecord
  belongs_to :proprietario

  validates :proprietario, presence: true
  validates :endereco, length: { maximum: 250 }, presence: true
  validates :area_terreno, :area_construida, :area_total, :aliquota, 
            :valor_venal_terreno, :valor_venal_construcao, 
            :valor_venal_total, :aliquota_aplicada, :valor_imposto, presence: true
  
  before_validation :calc_area_total, :calc_valor_venal_total, :calc_imposto

  def calc_area_total
    self.area_total = self.area_terreno + self.area_construida if self.area_terreno.present? and self.area_construida.present?
  end

  def calc_valor_venal_total
    self.valor_venal_total = self.valor_venal_terreno + self.valor_venal_construcao if self.valor_venal_terreno.present? and self.valor_venal_construcao.present?
  end

  def calc_imposto
    self.valor_imposto = self.valor_venal_total * (self.aliquota / 100) if self.valor_venal_total.present? and self.aliquota.present?
  end
end

app/models/proprietario.rb
# == Schema Information
#
# Table name: proprietarios
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  nome                   :string
#  endereco               :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Proprietario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :nome, length: { maximum: 100 }, presence: true
  validates :endereco, length: { maximum: 250 }, presence: true
  validates :role, presence: true

  has_many :imoveis, dependent: :destroy

  enum role: [:admin, :normal]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper
	
	before_action :authenticate_proprietario!
	before_action :configure_permitted_parameters, if: :devise_controller?
	
	rescue_from CanCan::AccessDenied do |exception|
		redirect_to '/', :alert => exception.message
	end
	
	rescue_from ActiveRecord::RecordNotFound, :with => :render_404
	
	def render_404
		redirect_to main_app.root_url
	end
	
	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:nome, :role, :endereco])
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/imoveis_controller.rb
class ImoveisController < ApplicationController
  before_action :set_imovel, only: [:edit, :update, :destroy]

  def index
    @imoveis = Imovel.all.page params[:page]
  end

  def new
    @imovel = Imovel.new
  end

  def create
    @imovel = Imovel.new(imovel_params)

    respond_to do |format|
      if @imovel.save
        flash[:success] = 'Imóvel criado com sucesso!'
        format.js { redirect_to imoveis_path }
      else
        format.js { render :new } 
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @imovel.update(imovel_params)
        flash[:success] = 'Imóvel atualizado com sucesso!'
        format.js { redirect_to imoveis_path }
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @imovel.destroy
    flash[:notice] = 'Imóvel deletado com sucesso!'
    redirect_to imoveis_path
  end

  private 

  def set_imovel
    @imovel = Imovel.find(params[:id])
  end

  def imovel_params
    params.require(:imovel).permit(:proprietario_id, :endereco, :area_terreno, 
                                   :area_construida, :aliquota, :valor_venal_terreno, 
                                   :valor_venal_construcao, :valor_venal_total, :aliquota_aplicada, :area_total, :valor_imposto)
  end
end

app/controllers/proprietarios_controller.rb
class ProprietariosController < ApplicationController
  before_action :set_proprietario, only: [:show, :edit, :update, :destroy]

  def index
    @proprietarios = Proprietario.all.page params[:page]
  end

  def edit
  end

  def new
    @proprietario = Proprietario.new
  end

  def create
    @proprietario = Proprietario.new(proprietario_params)

    respond_to do |format|
      if @proprietario.save
        flash[:success] = 'Proprietário cadastrado com sucesso!'
        format.js { redirect_to proprietarios_path }
      else
        format.js { render :new } 
      end
    end
  end

  def update
    respond_to do |format|
      if @proprietario.update(proprietario_params)
        flash[:success] = 'Proprietário atualizado com sucesso!'
        format.js { redirect_to proprietarios_path }
      else
        format.js { render :edit }
      end
    end
  end

  def destroy
    @proprietario.destroy
    flash[:notice] = 'Proprietário deletado com sucesso!'
    redirect_to proprietarios_path
  end

  private 
  
  def set_proprietario
    @proprietario = Proprietario.find(params[:id])
  end

  def proprietario_params
    params.require(:proprietario).permit(:nome, :endereco, :email, :role, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice'  then "alert alert-info alert-dismissible fade show"
      when 'success' then "alert alert-success alert-dismissible fade show"
      when 'error'   then "alert alert-danger alert-dismissible fade show"
      when 'alert'   then "alert alert-warning alert-dismissible fade show"
    end
  end

  def current_auth_resource
    if proprietario_signed_in?
      current_proprietario
    end
  end

  def current_ability
    @current_ability or @current_ability = Ability.new(current_auth_resource)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imoveis_helper.rb
module ImoveisHelper
end

app/helpers/proprietarios_helper.rb
module ProprietariosHelper
end

app/views/home/index.html.haml
.container
  .jumbotron
    %h1.display-4  Cadastro de Imóveis
    %p.lead="Usuário: #{current_proprietario.email}"
    %hr.my-4
    = link_to imoveis_path, class: 'btn btn-outline-primary btn-lg' do
      %i.fas.fa-home
      Lista de Imóveis

app/views/imoveis/_form.html.haml
= render 'layouts/flash_message'
= simple_form_for @imovel, remote: true do |f|
  .form-row
    .col
      = f.association :proprietario, label_method: :nome, value_method: :id, include_blank: 'Selecione o Proprietário'
  .form-group
    = f.input :endereco, placeholder: 'Formato: Rua x, nº xxxxx', input_html: {id: 'end_imovel'}

  .form-row
    .col
      = f.input :area_terreno, label: 'Área do Terreno', required: true, input_html: { step: 0.0, value: @imovel.area_terreno }, hint: 'Em m²', placeholder: '0.0'
    .col 
      = f.input :area_construida, label: 'Área Construída', required: true, input_html: { step: 0.0, value: @imovel.area_construida }, hint: 'Em m²', placeholder: '0.0'

  .form-row
    .col
      = f.input :valor_venal_terreno, required: true, hint: 'Valor em R$', placeholder: '0.0', input_html: { step: 0.0, value: @imovel.valor_venal_terreno }
    .col
      = f.input :valor_venal_construcao, required: true, hint: 'Valor em R$', placeholder: '0.0', input_html: { step: 0.0, value: @imovel.valor_venal_construcao } 
 
  .form-row
    .col
      = f.input :aliquota, label: 'Alíquota', required: true, hint: 'Valor em %', placeholder: '0.0', input_html: { step: 0.0, value: @imovel.aliquota }
    .col
      = f.input :aliquota_aplicada, required: true, hint: 'Valor em %', placeholder: '0.0', input_html: { step: 0.0, value: @imovel.aliquota_aplicada }
  
  - unless @imovel.new_record?
    %hr
    %h5.my-4 Valores Totais

    .form-row 
      .col
        = f.input :valor_imposto, input_html: { step: 0.0, value: @imovel.valor_imposto }, readonly: true
      .col
        = f.input :valor_venal_total, input_html: { value: @imovel.valor_venal_total }, readonly: true
      .col
        = f.input :area_total, input_html: { value: @imovel.area_total }, readonly: true

      
  .d-flex.justify-content-end
    %button.btn.btn-dark.mr-1{"data-dismiss" => "modal", :type => "button"} 
      %i.fas.fa-times
      Cancelar

    %button.btn.btn-primary.mr-1{type: 'submit', id: 'btn_submit_imovel'}
      %i.fas.fa-plus
      Salvar

app/views/imoveis/_lista.html.haml
.table-responsive
  %table.table-striped.table-bordered.table-hover.table-sm.w-100
    %caption Tabela de Imóveis
    %thead
      %tr.text-center
        %th #
        %th Proprietário
        %th Endereço
        %th Área Terreno
        %th Área Construída
        %th Alíquota
        %th Valor Venal Terreno
        %th Valor Venal Construção
        %th Alíquota Aplicada
        %th.table-info Área Total
        %th.table-primary Valor Venal Total
        %th.table-warning Valor Imposto
        %th 
          %i.fas.fa-cogs{title: 'Edição'}
    %tbody
      - @imoveis.each_with_index do |imovel, index|
        %tr.text-center.text-monospace
          %td=index+1
          %td.text-left= link_to "#{imovel.proprietario.nome}", proprietario_path(imovel.proprietario), remote: true, class: 'text-decoration-none', title: 'Clique para ver o proprietário'
          %td.small=imovel.endereco.truncate(25)
          %td=imovel.area_terreno
          %td=imovel.area_construida
          %td=number_to_percentage(imovel.aliquota, precision: 2)
          %td=number_to_currency(imovel.valor_venal_terreno)
          %td=number_to_currency(imovel.valor_venal_construcao)
          %td=number_to_percentage(imovel.aliquota_aplicada, precision: 2)
          %td.table-info=imovel.area_total
          %td.table-primary=number_to_currency(imovel.valor_venal_total)
          %td.table-warning=number_to_currency(imovel.valor_imposto)
          %td
            - if can? :crud, imovel
              = link_to edit_imovel_path(imovel), remote: true, class: 'btn btn-outline-dark btn-sm', title: 'Editar' do
                %i.fas.fa-edit
              = link_to imovel_path(imovel), method: :delete, data: {confirm: "Apagar Imóvel #{index + 1} ?"}, class: 'btn btn-outline-dark btn-sm mx-1', title: 'Apagar' do
                %i.fas.fa-trash
            - else 
              %i.fas.fa-exclamation-circle{title: 'Não autorizado'}

= paginate @imoveis

app/views/imoveis/edit.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'imoveis/edit.html.haml')}");
  modal.find('.modal-title').html("Atualizando Imóvel");
  modal.modal();

app/views/imoveis/index.html.haml
.card
  .card-header.d-flex.justify-content-between.align-items-center
    %h2 Lista de Imóveis

    = link_to new_imovel_path, remote: true, class: 'btn btn-primary', title: 'Novo imóvel' do
      %i.fas.fa-plus
      Novo

  .card-body
    - if @imoveis.present?  
      = render 'imoveis/lista'
    - else
      %p.text-muted Nenhum imóvel cadastrado no momento

app/views/imoveis/new.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'imoveis/new.html.haml')}");
  modal.find('.modal-title').html("Cadastrando Imóvel");
  modal.modal();

app/views/layouts/_flash_message.html.haml
- flash.each do |key, value|
	%div{:class => "#{flash_class(key)}"}
		= value
		%button.close{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
			%span{"aria-hidden" => "true"} ×

app/views/layouts/_modal.html.haml
#modal-window.modal.fade.bd-example-modal-lg{"aria-hidden" => "true", "aria-labelledby" => "myLargeModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg{:role => "document"}
    .modal-content
      .modal-header
        %h5.modal-title
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', type: 'button'}
          %span{'aria-hidden' => 'true'} ×
      .modal-body
        Aguarde...

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container
    = link_to 'Cadastro de Imóveis', root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarNavDropdown", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavDropdown", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarNavDropdown.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li.nav-item
          = link_to 'Home', root_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Imóveis', imoveis_path, class: 'nav-link'
        %li.nav-item
          = link_to 'Proprietários', proprietarios_path, class: 'nav-link'
      - if proprietario_signed_in?
        = link_to destroy_proprietario_session_path, method: :delete, class: 'btn btn-outline-secondary btn-sm', title: 'Sair' do
          %i.fas.fa-sign-out-alt
          Sair

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Intersol
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/navbar'
    .container-fluid
      .my-5
        = render 'layouts/flash_message'
        = yield
        = render 'layouts/modal'

app/views/proprietarios/_form.html.haml
= render 'layouts/flash_message'
= simple_form_for @proprietario, remote: true do |f|
  .form-row
    .col
      = f.input :nome, placeholder: 'Nome completo'
    .col
      = f.input :email, placeholder: 'Email'
  .form-group
    = f.input :endereco, placeholder: 'Formato: Rua x, nº xxxxx'
  .form-row
    .col
      = f.input :password, placeholder: '*******'
    .col
      = f.input :password_confirmation, placeholder: '*******'
  - if can? :manage, @proprietario
    .form-group
      = f.input :role, as: :radio_buttons, collection: [['0', 'admin'], ['1', 'normal']], label_method: :second, value_method: :second
    
  .d-flex.justify-content-end
    %button.btn.btn-dark.mr-1{"data-dismiss" => "modal", :type => "button"} 
      %i.fas.fa-times
      Cancelar

    %button.btn.btn-primary.mr-1{type: 'submit', id: 'btn_submit_imovel'}
      %i.fas.fa-plus
      Salvar

app/views/proprietarios/_lista.html.haml
.table-responsive
  %table.table-striped.table-bordered.table-hover.table-sm.w-100
    %caption Tabela de Proprietários
    %thead
      %tr.text-center
        %th #
        %th Nome
        %th Email
        %th Endereço
        %th 
          %i.fas.fa-cogs{title: 'Edição'}
    %tbody
      - @proprietarios.each_with_index do |prop, index|
        %tr.text-center.text-monospace
          %td=index+1
          %td= link_to "#{prop.nome}", proprietario_path(prop), remote: true, class: 'text-decoration-none', title: 'Detalhes do proprietário'
          %td=prop.email
          %td.small=prop.endereco.truncate(25)
          
          %td
            - if can? :crud, prop
              = link_to edit_proprietario_path(prop), remote: true, class: 'btn btn-outline-dark btn-sm', title: 'Editar' do
                %i.fas.fa-edit
              - unless prop.eql?(current_proprietario)
                = link_to proprietario_path(prop), method: :delete, data: {confirm: "Apagar Proprietário #{prop.nome} ?"}, class: 'btn btn-outline-dark btn-sm mx-1', title: 'Apagar' do
                  %i.fas.fa-trash
            - else 
              %i.fas.fa-exclamation-circle{title: 'Não autorizado'}

= paginate @proprietarios

app/views/proprietarios/edit.html.haml
= render 'form'

app/views/proprietarios/edit.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'proprietarios/edit.html.haml')}");
  modal.find('.modal-title').html("Editar Proprietário");
  modal.modal();

app/views/proprietarios/index.html.haml
.card
  .card-header.d-flex.justify-content-between.align-items-center
    %h2 Proprietários
    
    - if can? :manage, Proprietario
      = link_to new_proprietario_path, remote: true, class: 'btn btn-primary', title: 'Novo proprietário' do
        %i.fas.fa-plus
        Novo

  .card-body
    - if @proprietarios.present?  
      = render 'proprietarios/lista'

app/views/proprietarios/new.html.haml
= render 'form'

app/views/proprietarios/new.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'proprietarios/new.html.haml')}");
  modal.find('.modal-title').html("Cadastrando Proprietário");
  modal.modal();

app/views/proprietarios/show.html.haml
.media
  %i.fas.fa-user.fa-7x.mr-3
  .media-body
    = "Tipo: #{ @proprietario.role.titleize }"
    %h5.mt-0= @proprietario.nome
    %p.text-muted= @proprietario.endereco

app/views/proprietarios/show.js.haml
:plain
  var modal = $("#modal-window")
  modal.find(".modal-body").html("#{j (render file: 'proprietarios/show.html.haml')}");
  modal.find('.modal-title').html("Detalhes do Proprietário");
  modal.modal();